						<div class = "work_section article_section two_column full_width white">
							<div class = "fixed_width">
								<p>Microsoft is set to become the latest tech giant to develop its own tracking technology to replace the ubiquitous "cookie," which has become the focus of regulators and privacy advocates.</p>
								
								<p>The company is internally developing the technology that would enable tracking across desktop computers, tablets and smartphones running Windows, as well as the company's Xbox gaming console and services including its Internet Explorer web browser and Bing search engine, according to sources close to the company not authorized to speak publicly about Microsoft's plans.</p>
								
								<p>Google is similarly plotting its own cookie replacement, and others such as Facebook, Apple and Amazon are expected to pounce on the third-party cookie's vulnerability. The technology has served as the foundation for targeted online advertising by enabling browsing behavior to be tracked across sites and used to target ads. However third-party cookies are limited in that they cannot track mobile devices, which account for 20% of global web traffic, according to Statcounter.</p>
								
								<p>Cookies are also irrelevant to TV and web-delivered video services, a limitation that leads some to predict the technology will become extinct. "For the past two to three years now, there has been a lot of talk about the impending death of the third-party cookie," said Michael Schoen, EVP-programmatic product management at IPG Mediabrands..</p>
								
								<p>Microsoft's plans are in the early stages with no clear picture on when the replacement would complete its roll-out across all devices, though Xbox is said to be on the latter end of that roadmap. "We agree that going beyond the cookie is important. Our priority will be to find ways to do this that respect the interests of consumers," a Microsoft spokesperson said in an email.</p>
								
								<p>Device identifier
								<p>Microsoft's cookie replacement would essentially be a device identifier, meaning consumers could give permission for its advertising use when opting in to a device's regular user agreement or terms of service. Microsoft would then become directly responsible for users' data and -- assuming it doesn't share it with third parties -- confine privacy concerns to the Redmond, Wash.-based company rather than countless companies that currently collect data on people's browsing behaviors.</p>
								
								<p>By contrast, the cookie is a technology that isn't owned by one company and allowed a standard means of tracking web browsers that allowed a huge third-party ad ecosystem to bloom. Replacing it with propietary technologies would consolidate power with Google, Facebook, Microsoft, Apple, Amazon and others with large opt-in audiences.</p>
								
								<p>While different technology and privacy standards would be a headache for advertisers, it might make the Federal Trade Commission's job easier by giving it fewer companies to keep an eye on since they control the mediating technology of advertising.</p>
								
								<p>But it could also raise competitive issues because the owners of these technologies such as Google and Microsoft could see data generated by the advertisers, agencies and ad tech companies using them. They could also restrict the use of their technologies for their own sites and apps, indirectly coercing advertisers to funnel budgets their way.</p>
								
								<p>Connecting mobile devices
								<p>At a basic level, Microsoft's cookie replacement would take what's already possible on desktop web browsers with third-party cookies and extend it to new devices like smartphones and connected TVs. For example, digital music video network Vevo could run a restaurant advertiser's video spot in its Xbox app, then follow up with display banners targeted to viewers of that video ad when they check out Vevo's app on their Surface tablet. Vevo could even add a banner in its Windows Phone app aimed to drive foot traffic for the restaurant.</p>
								
								<p>Microsoft's cookie replacement could also factor in behavioral data from company-owned services like Internet Explorer and Bing, sources said, meaning intent-laden search data could inform TV-style ads within streaming video apps on Xbox.</p>
								
								<p>Microsoft's move to create a cookie replacement could further aggravate those already up in arms over the new Internet Explorer browser, which has a do-not-track setting by default. It's unclear how many advertisers are honoring that request, however, and that call was made by the team behind Internet Explorer, not Microsoft's advertising team, which is behind the new tracking technology.</p>
								
								<p>Advertisers have been pressuring tech companies to move beyond the cookie because of its inability to bridge desktop and mobile devices. Because of that limitation, an advertiser can't know if the desktop banner they ran led to a purchase made on the smartphone.</p>
								
								<p>"In terms of identifying the same user across platforms, there has to be another way," said eMarketer analyst Lauren Fisher.</p>
								
								<p>"Not only would [Microsoft] be building out an ad ID, but they would also be building out a cross-channel attribution model, which everybody wants," said The Media Kitchen president Barry Lowenthal.</p>
																
								<p>While Microsoft counts 1.5 billion people who use its services like Windows, Outlook, Internet Explorer and Xbox every day, research firm IDC projects Microsoft's smartphone operating system's market share at 3.9% globally compared to 75.3% for Google's Android and 16.9% for Apple's iOS.</p>
								
								<p>On the other hand, a cookie replacement that would work on Xbox would likely fuel advertiser interest, considering the gaming console has become more of a connected TV device. Last year 46 million people consumed 18 billion hours of non-gaming entertainment such as movies and TV shows on the console, Xbox marketing executive Yusuf Mehdi said earlier this year. "That's a strong audience base that would certainly be a benefit," Ms. Fisher said.</p>
								
								<p>"It's a great opportunity to connect the typical digital channel with the TV channel," Mr. Schoen said.	</p>						
							
								<div class = "button"><a href = "http://adage.com/article/digital/microsoft-cookie-replacement-span-desktop-mobile-xbox/244638/?codekitCB=403024368.860966" target = "_blank" >View Article at AdAge.com</a></div>
							</div>
						</div>
